[package]
name = "twitter_service"
version = "0.1.0"
authors = ["user <jobmail862@gmail.com>"]

[dependencies]
reqwest = "0.8.6"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
base64 = "0.9.2"
hyper = "0.12"
mysql = "*"